In [149]:
import pandas as pd
import numpy as np

#creation du data set 
array = np.array(
[
[1,0,0,0,1,0,1,1,0,1],
[0,1,0,1,1,0,1,0,1,0],
[1,0,0,1,1,1,0,1,0,1],
[0,1,0,1,0,1,1,0,1,1],
[1,0,0,1,0,0,0,0,1,0],
[0,1,0,0,0,0,0,1,1,0],
[1,0,1,0,1,0,1,0,1,1],
[0,1,1,1,0,1,0,0,0,1]
]
)
y = [20,50,70,10,34,12,90,7,3,23]
X = pd.DataFrame(data = array).T
X.columns = ["Présence de Crudités","Présence de Légumes","Présence de Féculents",
             "Présence de Charcuteries",'Présence de Garnitures','Présence de Viandes'
             ,'Présence de Fromages','Présence de Dessert']

In [150]:
X

Présence de Crudités  Présence de Légumes  Présence de Féculents  \
0                     1                    0                      1   
1                     0                    1                      0   
2                     0                    0                      0   
3                     0                    1                      1   
4                     1                    1                      1   
5                     0                    0                      1   
6                     1                    1                      0   
7                     1                    0                      1   
8                     0                    1                      0   
9                     1                    0                      1   

   Présence de Charcuteries  Présence de Garnitures  Présence de Viandes  \
0                         0                       1                    0   
1                         1                       0                    1   
2                         0                       0                    0   
3                         1                       1                    0   
4                         0                       0                    0   
5                         1                       0                    0   
6                         1                       0                    0   
7                         0                       0                    1   
8                         1                       1                    1   
9                         1                       0                    0   

   Présence de Fromages  Présence de Dessert  
0                     1                    0  
1                     0                    1  
2                     1                    1  
3                     0                    1  
4                     1                    0  
5                     0                    1  
6                     1                    0  
7                     0                    0  
8                     1                    0  
9                     1                    1

In [151]:
reg = LinearRegression().fit(X,y) # Regression linaire Multiple (8) cacule de la droite linaire 
reg.coef_

array([ 37.5,   8. , -71. , -14. ,  -7.5, -42. , -25. ,  12. ])

In [138]:
reg.intercept_ # +b

84.00000000000009

In [146]:
reg.predict(X) #esseyer de predire X

array([18. , 48. , 71. , 11.5, 33.5, 11. , 90.5,  8.5,  3.5, 23.5])

In [140]:
y #Le comparer avec les taux on remarque pas beaucoup de difference notre model est pas si mauvais ^^

[20, 50, 70, 10, 34, 12, 90, 7, 3, 23]

In [168]:
array = np.array(
[
[1],
[1],
[1],
[0],
[0],
[0],
[0],
[0]
]
)

X_test = pd.DataFrame(data = array).T
X_test.columns = ["Présence de Crudités","Présence de Légumes","Présence de Féculents",
             "Présence de Charcuteries",'Présence de Garnitures','Présence de Viandes'
             ,'Présence de Fromages','Présence de Dessert']

In [158]:
X_test


Présence de Crudités  Présence de Légumes  Présence de Féculents  \
0                     1                    0                      0   

   Présence de Charcuteries  Présence de Garnitures  Présence de Viandes  \
0                         1                       1                    1   

   Présence de Fromages  Présence de Dessert  
0                     1                    0

In [159]:
reg.coef_

array([ 37.5,   8. , -71. , -14. ,  -7.5, -42. , -25. ,  12. ])

In [169]:
reg.predict(X_test) #prediction du taux X teste

array([84.])